// Example country data for targeting, can be expanded
export const COUNTRIES = [
  { name: "United States", code: "US", tier: 1 },
  { name: "United Kingdom", code: "GB", tier: 1 },
  { name: "Canada", code: "CA", tier: 1 },
  { name: "Germany", code: "DE", tier: 1 },
  { name: "France", code: "FR", tier: 1 },
  { name: "Japan", code: "JP", tier: 1 },
  { name: "Australia", code: "AU", tier: 1 },
  { name: "Italy", code: "IT", tier: 2 },
  { name: "Spain", code: "ES", tier: 2 },
  { name: "Netherlands", code: "NL", tier: 2 },
  { name: "Sweden", code: "SE", tier: 2 },
  { name: "Switzerland", code: "CH", tier: 2 },
  { name: "Norway", code: "NO", tier: 2 },
  { name: "Finland", code: "FI", tier: 2 },
  { name: "Denmark", code: "DK", tier: 2 },
  { name: "Belgium", code: "BE", tier: 2 },
  { name: "Austria", code: "AT", tier: 2 },
  { name: "Ireland", code: "IE", tier: 2 },
  { name: "New Zealand", code: "NZ", tier: 2 },
  { name: "Kenya", code: "KE", tier: 3 },
  { name: "Uganda", code: "UG", tier: 3 },
  { name: "Nigeria", code: "NG", tier: 3 },
  { name: "South Africa", code: "ZA", tier: 3 },
  { name: "India", code: "IN", tier: 3 },
  { name: "Brazil", code: "BR", tier: 3 },
  { name: "China", code: "CN", tier: 3 },
  { name: "Russia", code: "RU", tier: 3 },
  { name: "Mexico", code: "MX", tier: 3 },
  { name: "Turkey", code: "TR", tier: 3 },
  { name: "Egypt", code: "EG", tier: 3 },
  { name: "Ghana", code: "GH", tier: 3 },
  { name: "Tanzania", code: "TZ", tier: 3 },
  { name: "Rwanda", code: "RW", tier: 3 },
];
